extends Node
class_name Items

const maximum:int = 9999
var content:Dictionary = {
	1: {
		"caption": "items.log.caption", 
		"description": "items.log.description", 
		"type": "items.type.building_materials", #
		"item_type": 'building materials',
		"purchase": 30,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/log.png"),
	},
	2: {
		"caption": "items.plank.caption",
		"description": "items.plank.description",
		"type": "items.type.building_materials",
		"item_type": 'building materials',
		"purchase": 40,
		"sale": 15,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/plank.png"),
	},
	3: {
		"caption": "items.stone.caption",
		"description": "items.stone.description",
		"type": "items.type.building_materials",
		"item_type": 'building materials',
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/stone.png"),
	},
	4: {
		"caption": "items.cobblestone.caption",
		"description": "items.cobblestone.description",
		"type": "items.type.building_materials",
		"item_type": 'building_materials',
		"purchase": 40,
		"sale": 10,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/cobblestone.png"),
	},
	5: {
		"caption": "items.coal.caption",
		"description": "items.coal.description",
		"type": "items.type.ores",
		"item_type": "fuel",
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/coal.png"),
	},
	6: {
		"caption": "items.copper_ore.caption",
		"description": "items.copper_ore.description",
		"type": "items.type.ores",
		"item_type": "ore",
		"oven_result": 9,
		"purchase": 50,
		"sale": 10,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/copper_ore.png"),
	},
	7: {
		"caption": "items.iron_ore.caption",
		"description": "items.iron_ore.description",
		"type": "items.type.ores",
		"item_type": "ore",
		"oven_result": 10,
		"purchase": 75,
		"sale": 10,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/iron_ore.png"),
	},
	8: {
		"caption": "items.bauxite_ore.caption",
		"description": "items.bauxite_ore.description",
		"type": "items.type.ores",
		"item_type": "ore",
		"oven_result": 11,
		"purchase": 100,
		"sale": 125,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/bauxite_ore.png"),
	},
	9: {
		"caption": "items.copper_ingot.caption",
		"description": "items.copper_ingot.description",
		"type": "items.type.building_materials",
		"item_type": 'building_materials',
		"purchase": 400,
		"sale": 100,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/copper_ingot.png"),
	},
	10: {
		"caption": "items.iron_ingot.caption",
		"description": "items.iron_ingot.description",
		"type": "items.type.building_materials",
		"item_type": 'building_materials',
		"purchase": 600,
		"sale": 150,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/iron_ingot.png"),
	},
	11: {
		"caption": "items.aluminum_ingot.caption",
		"description": "items.aluminum_ingot.description",
		"type": "items.type.building_materials",
		"item_type": 'building_materials',
		"purchase": 750,
		"sale": 200,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	},
	#	-1: {
	#		"caption": "Аметист"),
	#		"description": "Редкий драгоценный камень, используемый для украшений или магических целей"),
	#		"type": "items.type.building_materials")),
	#		"item_type": 'building_materials',
	#		"purchase": 100,
	#		"sale": 25,
	#		"icon": preload("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	#	},
	# seeds packets
	13: {
		"caption": "items.carrot_seeds.caption",
		"description": "items.carrot_seeds.description",
		#	"specifications": {
		#		"growth": "carrot.growth"),
		#		"productivity": "carrot.productivity"),
		#		"conditions": "carrot.conditions"),
		#	},
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 15,
		"sale": 5,
		"crop": 1,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_1.png"),
	},
	14: {
		"caption": "items.potato_seeds.caption",
		"description": "items.potato_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 40,
		"sale": 10,
		"crop": 2,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_2.png"),
	},
	15: {
		"caption": "items.radish_seeds.caption",
		"description": "items.radish_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 25,
		"sale": 5,
		"crop": 3,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_3.png"),
	},
	16: {
		"caption": "items.cabbage_seeds.caption",
		"description": "items.cabbage_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 60,
		"sale": 25,
		"crop": 4,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_4.png"),
	},
	17: {
		"caption": "items.onion_seeds.caption",
		"description": "items.onion_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 35,
		"sale": 15,
		"crop": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_5.png"),
	},
	18: {
		"caption": "items.cucumber_seeds.caption",
		"description": "items.cucumber_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 25,
		"sale": 5,
		"crop": 6,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_6.png"),
	},
	19: {
		"caption": "items.tomato_seeds.caption",
		"description": "items.tomato_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 40,
		"sale": 20,
		"crop": 7,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_7.png"),
	},
	20: {
		"caption": "items.eggplant_seeds.caption",
		"description": "items.eggplant_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 50,
		"sale": 25,
		"crop": 8,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_8.png"),
	},
	21: {
		"caption": "items.pepper_seeds.caption",
		"description": "items.pepper_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 30,
		"sale": 15,
		"crop": 9,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_9.png"),
	},
	22: {
		"caption": "items.corn_seeds.caption",
		"description": "items.corn_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 75,
		"sale": 30,
		"crop": 10,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_10.png"),
	},
	23: {
		"caption": "items.parsnip_seeds.caption",
		"description": "items.parsnip_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 20,
		"sale": 5,
		"crop": 11,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_11.png"),
	},
	24: {
		"caption": "items.garlic_seeds.caption",
		"description": "items.garlic_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 35,
		"sale": 15,
		"crop": 12,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_12.png"),
	},
	25: {
		"caption": "items.beet_seeds.caption",
		"description": "items.beet_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 45,
		"sale": 25,
		"crop": 13,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_13.png"),
	},
	26: {
		"caption": "items.turnip_seeds.caption",
		"description": "items.turnip_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 50,
		"sale": 25,
		"crop": 14,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_14.png"),
	},
	27: {
		"caption": "items.bean_seeds.caption",
		"description": "items.bean_seeds.description",
		"type": 'items.type.seeds',
		"item_type": "seeds",
		"purchase": 60,
		"sale": 30,
		"crop": 15,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_15.png"),
	},
	# crops
	28: {
		"caption": "items.carrot.caption",
		"description": "items.carrot.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 100,
		"sale": 50,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/carrot.png"),
	},
	29: {
		"caption": "items.potato.caption",
		"description": "items.potato.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 125,
		"sale": 75,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/potato.png"),
	},
	30: {
		"caption": "items.radish.caption",
		"description": "items.radish.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 75,
		"sale": 60,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/radish.png"),
	},
	31: {
		"caption": "items.cabbage.caption",
		"description": "items.cabbage.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 150,
		"sale": 100,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/cabbage.png"),
	},
	32: {
		"caption": "items.onion.caption",
		"description": "items.onion.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 100,
		"sale": 75,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/onion.png"),
	},
	33: {
		"caption": "items.cucumber.caption",
		"description": "items.cucumber.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 100,
		"sale": 75,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/cucumber.png"),
	},
	34: {
		"caption": "items.tomato.caption",
		"description": "items.tomato.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 110,
		"sale": 80,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/tomato.png"),
	},
	35: {
		"caption": "items.eggplant.caption",
		"description": "items.eggplant.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 175,
		"sale": 125,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/eggplant.png"),
	},
	36: {
		"caption": "items.pepper.caption",
		"description": "items.pepper.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 105,
		"sale": 70,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/pepper.png"),
	},
	37: {
		"caption": "items.corn.caption",
		"description": "items.corn.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 175,
		"sale": 125,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/corn.png"),
	},
	38: {
		"caption": "items.parsnip.caption",
		"description": "items.parsnip.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 90,
		"sale": 65,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/parships.png"),
	},
	39: {
		"caption": "items.garlic.caption",
		"description": "items.garlic.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 115,
		"sale": 80,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/garlic.png"),
	},
	40: {
		"caption": "items.beet.caption",
		"description": "items.beet.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 125,
		"sale": 90,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/beet.png"),
	},
	41: {
		"caption": "items.turnip.caption",
		"description": "items.turnip.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 100,
		"sale": 75,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/turnip.png"),
	},
	42: {
		"caption": "items.bean.caption",
		"description": "items.bean.description",
		"type": 'items.type.harvest',
		"item_type": "crop",
		"purchase": 115,
		"sale": 90,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/crops/greenbeen.png"),
	},
	# spoiled crops
	43: {
		"caption": "items.rotten_carrot.caption",
		"description": "items.rotten_carrot.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_1.png"),
	},
	44: {
		"caption": "items.rotten_potato.caption",
		"description": "items.rotten_potato.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_2.png"),
	},
	45: {
		"caption": "items.rotten_radish.caption",
		"description": "items.rotten_radish.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_3.png"),
	},
	46: {
		"caption": "items.rotten_cabbage.caption",
		"description": "items.rotten_cabbage.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_4.png"),
	},
	47: {
		"caption": "items.rotten_onion.caption",
		"description": "items.rotten_onion.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_5.png"),
	},
	48: {
		"caption": "items.rotten_cucumber.caption",
		"description": "items.rotten_cucumber.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_6.png"),
	},
	49: {
		"caption": "items.rotten_tomato.caption",
		"description": "items.rotten_tomato.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_7.png"),
	},
	50: {
		"caption": "items.rotten_eggplant.caption",
		"description": "items.rotten_eggplant.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_8.png"),
	},
	51: {
		"caption": "items.rotten_pepper.caption",
		"description": "items.rotten_pepper.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_9.png"),
	},
	52: {
		"caption": "items.rotten_corn.caption",
		"description": "items.rotten_corn.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_10.png"),
	},
	53: {
		"caption": "items.rotten_parsnip.caption",
		"description": "items.rotten_parsnip.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_11.png"),
	},
	54: {
		"caption": "items.rotten_garlic.caption",
		"description": "items.rotten_garlic.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_12.png"),
	},
	55: {
		"caption": "items.rotten_beet.caption",
		"description": "items.rotten_beet.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_13.png"),
	},
	56: {
		"caption": "items.rotten_turnip.caption",
		"description": "items.rotten_turnip.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_14.png"),
	},
	57: {
		"caption": "items.rotten_beans.caption",
		"description": "items.rotten_beans.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_15.png"),
	},
	# trash
	58: {
		"caption": "items.crop_residue.caption",
		"description": "items.crop_residue.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/trash/trash_1.png"),
	},
	59: {
		"caption": "items.broken_branch.caption",
		"description": "items.broken_branch.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/trash/trash_2.png"),
	},
	60: {
		"caption": "items.weeds.caption",
		"description": "items.weeds.description",
		"type": "items.type.waste",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 25,
		"sale": 5,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/trash/trash_2.png"),
	},
	# Compost
	61: {
		"caption": "items.basic_compost.caption",
		"description": "items.basic_compost.description",
		"type": "items.type.fertilizer",
		"item_type": "fertilizer",
		"purchase": 150,
		"sale": 100,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/fertilizer.png"),
		"func": {
			"reducing": 5.0, # %
		},
	},
	62: {
		"caption": "items.premium_compost.caption",
		"description": "items.premium_compost.description",
		"type": "items.type.fertilizer",
		"item_type": "fertilizer",
		"purchase": 250,
		"sale": 150,
		"icon": preload("res://assets/resources/ui/interactive/inventory/items/high_fertilizer.png"),
		"func": {
			"reducing": 20.0, # %
		},
	},
}
