extends Node

class_name Items
const maximum:int = 9999
var content:Dictionary = {
	1: {
		"caption": tr("Бревно"),
		"description": tr("Простое деревянное бревно, полученное из деревьев. Используется для строительства."),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/log.png"),
	},
	2: {
		"caption": tr("Доска"),
		"description": tr("Обработанное бревно, готовое для использования в строительстве."),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/plank.png"),
	},
	3: {
		"caption": tr("Камень"),
		"description": tr("Твёрдый природный материал. Подходит для создания прочных конструкций"),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/stone.png"),
	},
	4: {
		"caption": tr("Булыжник"),
		"description": tr("Часто используемый для дорожек или декоративных элементов."),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/cobblestone.png"),
	},
	5: {
		"caption": tr("Уголь"),
		"description": tr("Горючий материал, добываемый из земли. Идеален для топлива или создания освещения."),
		"type": "Руда",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/coal.png"),
	},
	6: {
		"caption": tr("Медная руда"),
		"description": tr("После переплавки может быть использована для создания инструментов и деталей"),
		"type": "Руда",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/copper_ore.png"),
	},
	7: {
		"caption": tr("Железная руда"),
		"description": tr("Основа для прочных инструментов и конструкций"),
		"type": "Руда",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/iron_ore.png"),
	},
	8: {
		"caption": tr("Бокситовая руда"),
		"description": tr("Используется для создания лёгких и прочных материалов"),
		"type": "Руда",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/bauxite_ore.png"),
	},
	9: {
		"caption": tr("Медный слиток"),
		"description": tr("Очищенная медь, готовая для использования в строительстве"),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/copper_ingot.png"),
	},
	10: {
		"caption": tr("Железный слиток"),
		"description": tr("Прочный металл, подходящий для создания надёжных инструментов и конструкций"),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/iron_ingot.png"),
	},
	11: {
		"caption": tr("Алюминивый слиток"),
		"description": tr("Лёгкий и прочный металл, идеальный для современных конструкций"),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	},
	12: {
		"caption": tr("Аметист"),
		"description": tr("Редкий драгоценный камень, используемый для украшений или магических целей"),
		"type": "Строительные материалы",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	},
	# seeds packets
	13: {
		"caption": tr("Семена моркови"),
		"description": tr("Маленькие семена для выращивания моркови."),
		"specifications": {
			"growth": tr("carrot.growth"),
			"productivity": tr("carrot.productivity"),
			"conditions": tr("carrot.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 1,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_1.png"),
	},
	14: {
		"caption": tr("Семена картофеля"),
		"description": tr("Эти семена помогут вырастить питательный картофель."),
		"specifications": {
			"growth": tr("potato.growth"),
			"productivity": tr("potato.productivity"),
			"conditions": tr("potato.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 2,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_2.png"),
	},
	15: {
		"caption": tr("Семена редиса"),
		"description": tr("Маленькие семена для быстрого выращивания хрустящего редиса."),
		"specifications": {
			"growth": tr("radish.growth"),
			"productivity": tr("radish.productivity"),
			"conditions": tr("radish.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 3,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_3.png"),
	},
	16: {
		"caption": tr("Семена капусты"),
		"description": tr("Семена для выращивания плотной и сочной капусты."),
		"specifications": {
			"growth": tr("cabbage.growth"),
			"productivity": tr("cabbage.productivity"),
			"conditions": tr("cabbage.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 4,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_4.png"),
	},
	17: {
		"caption": tr("Семена репчатого лука"),
		"description": tr("Небольшие семена для выращивания сочного репчатого лука."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_5.png"),
	},
	18: {
		"caption": tr("Семена огурцов"),
		"description": tr("Семена для выращивания свежих и хрустящих огурцов."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 6,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_6.png"),
	},
	19: {
		"caption": tr("Семена томата"),
		"description": tr("Семена для выращивания ароматных помидоров."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 7,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_7.png"),
	},
	20: {
		"caption": tr("Семена баклажана"),
		"description": tr("Семена для выращивания баклажанов с гладкой фиолетовой кожурой."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 8,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_8.png"),
	},
	21: {
		"caption": tr("Семена перца"),
		"description": tr("Семена для выращивания сладкого перца"),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 9,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_9.png"),
	},
	22: {
		"caption": tr("Семена кукурузы"),
		"description": tr("Крупные семена для выращивания сладкой кукурузы."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 10,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_10.png"),
	},
	23: {
		"caption": tr("Семена пастернака"),
		"description": tr("Семена для выращивания ароматного пастернака."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 11,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_11.png"),
	},
	24: {
		"caption": tr("Зубчики чеснока"),
		"description": tr("Зубчики для выращивания острого чеснока."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 12,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_12.png"),
	},
	25: {
		"caption": tr("Семена свёклы"),
		"description": tr("Семена для выращивания сладкой и сочной свёклы."),
		"type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 13,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_13.png"),
	},
	# crops
	26: {
		"caption": tr("Морковь"),
		"description": tr("carrot_crop.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 25,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/carrot.png"),
	},
	27: {
		"caption": tr("Картофель"),
		"description": tr("potato_crop.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 75,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/potato.png"),
	},
	28: {
		"caption": tr("Редис"),
		"description": tr("radish_crop.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 50,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/radish.png"),
	},
	29: {
		"caption": tr("Кочан капусты"),
		"description": tr("cabbage_crop.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/cabbage.png"),
	},
	30: {
		"caption": tr("Репчатый лук"),
		"description": tr("onion_crop.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/onion.png"),
	},
	31: {
		"caption": tr("Огурец"),
		"description": tr("cucumber.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/cucumber.png"),
	},
	32: {
		"caption": tr("Помидор"),
		"description": tr("tomato.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/tomato.png"),
	},
	33: {
		"caption": tr("Баклажан"),
		"description": tr("eggplant.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/eggplant.png"),
	},
	34: {
		"caption": tr("Перец"),
		"description": tr("pepper.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/pepper.png"),
	},
	35: {
		"caption": tr("Початок кукурузы"),
		"description": tr("corn.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/corn.png"),
	},
	36: {
		"caption": tr("Пастернак"),
		"description": tr("parships.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/parships.png"),
	},
	37: {
		"caption": tr("Чеснок"),
		"description": tr("garlic.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/garlic.png"),
	},
	38: {
		"caption": tr("Свёкла"),
		"description": tr("beet.description"),
		"type": "Урожай",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/beet.png"),
	},
}
