extends Node

class_name Items
const maximum:int = 9999
var content:Dictionary = {
	1: {
		"caption": tr("Бревно"),
		"description": tr("Простое деревянное бревно, полученное из деревьев. Используется для строительства."),
		"type": "Строительные материалы",
		"item_type": 'building materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/log.png"),
	},
	2: {
		"caption": tr("Доска"),
		"description": tr("Обработанное бревно, готовое для использования в строительстве."),
		"type": "Строительные материалы",
		"item_type": 'building materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/plank.png"),
	},
	3: {
		"caption": tr("Камень"),
		"description": tr("Твёрдый природный материал. Подходит для создания прочных конструкций"),
		"type": "Строительные материалы",
		"item_type": 'building materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/stone.png"),
	},
	4: {
		"caption": tr("Булыжник"),
		"description": tr("Часто используемый для дорожек или декоративных элементов."),
		"type": "Строительные материалы",
		"item_type": 'building_materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/cobblestone.png"),
	},
	5: {
		"caption": tr("Уголь"),
		"description": tr("Горючий материал, добываемый из земли. Идеален для топлива или создания освещения."),
		"type": "Руда",
		"item_type": "ores",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/coal.png"),
	},
	6: {
		"caption": tr("Медная руда"),
		"description": tr("После переплавки может быть использована для создания инструментов и деталей"),
		"type": "Руда",
		"item_type": "ores",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/copper_ore.png"),
	},
	7: {
		"caption": tr("Железная руда"),
		"description": tr("Основа для прочных инструментов и конструкций"),
		"type": "Руда",
		"item_type": "ores",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/iron_ore.png"),
	},
	8: {
		"caption": tr("Бокситовая руда"),
		"description": tr("Используется для создания лёгких и прочных материалов"),
		"type": "Руда",
		"item_type": "ores",
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/bauxite_ore.png"),
	},
	9: {
		"caption": tr("Медный слиток"),
		"description": tr("Очищенная медь, готовая для использования в строительстве"),
		"type": "Строительные материалы",
		"item_type": 'building_materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/copper_ingot.png"),
	},
	10: {
		"caption": tr("Железный слиток"),
		"description": tr("Прочный металл, подходящий для создания надёжных инструментов и конструкций"),
		"type": "Строительные материалы",
		"item_type": 'building_materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/iron_ingot.png"),
	},
	11: {
		"caption": tr("Алюминивый слиток"),
		"description": tr("Лёгкий и прочный металл, идеальный для современных конструкций"),
		"type": "Строительные материалы",
		"item_type": 'building_materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	},
	-1: {
		"caption": tr("Аметист"),
		"description": tr("Редкий драгоценный камень, используемый для украшений или магических целей"),
		"type": "Строительные материалы",
		"item_type": 'building_materials',
		"purchase": 1,
		"sale": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	},
	# seeds packets
	13: {
		"caption": tr("Семена моркови"),
		"description": tr("Маленькие семена для выращивания моркови."),
		"specifications": {
			"growth": tr("carrot.growth"),
			"productivity": tr("carrot.productivity"),
			"conditions": tr("carrot.conditions"),
		},
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 1,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_1.png"),
	},
	14: {
		"caption": tr("Семена картофеля"),
		"description": tr("Эти семена помогут вырастить питательный картофель."),
		"specifications": {
			"growth": tr("potato.growth"),
			"productivity": tr("potato.productivity"),
			"conditions": tr("potato.conditions"),
		},
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 2,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_2.png"),
	},
	15: {
		"caption": tr("Семена редиса"),
		"description": tr("Маленькие семена для быстрого выращивания хрустящего редиса."),
		"specifications": {
			"growth": tr("radish.growth"),
			"productivity": tr("radish.productivity"),
			"conditions": tr("radish.conditions"),
		},
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 3,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_3.png"),
	},
	16: {
		"caption": tr("Семена капусты"),
		"description": tr("Семена для выращивания плотной и сочной капусты."),
		"specifications": {
			"growth": tr("cabbage.growth"),
			"productivity": tr("cabbage.productivity"),
			"conditions": tr("cabbage.conditions"),
		},
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 5,
		"crop": 4,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_4.png"),
	},
	17: {
		"caption": tr("Семена репчатого лука"),
		"description": tr("Небольшие семена для выращивания сочного репчатого лука."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 5,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_5.png"),
	},
	18: {
		"caption": tr("Семена огурцов"),
		"description": tr("Семена для выращивания свежих и хрустящих огурцов."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 6,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_6.png"),
	},
	19: {
		"caption": tr("Семена томата"),
		"description": tr("Семена для выращивания ароматных помидоров."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 7,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_7.png"),
	},
	20: {
		"caption": tr("Семена баклажана"),
		"description": tr("Семена для выращивания баклажанов с гладкой фиолетовой кожурой."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 8,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_8.png"),
	},
	21: {
		"caption": tr("Семена перца"),
		"description": tr("Семена для выращивания сладкого перца"),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 9,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_9.png"),
	},
	22: {
		"caption": tr("Семена кукурузы"),
		"description": tr("Крупные семена для выращивания сладкой кукурузы."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 10,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_10.png"),
	},
	23: {
		"caption": tr("Семена пастернака"),
		"description": tr("Семена для выращивания ароматного пастернака."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 11,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_11.png"),
	},
	24: {
		"caption": tr("Семена чеснока"),
		"description": tr("Зубчики для выращивания острого чеснока."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 12,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_12.png"),
	},
	25: {
		"caption": tr("Семена свёклы"),
		"description": tr("Семена для выращивания сладкой и сочной свёклы."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 13,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_13.png"),
	},
	26: {
		"caption": tr("Семена репы"),
		"description": tr("Семена для выращивания сладкой и сочной свёклы."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 14,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_14.png"),
	},
	27: {
		"caption": tr("Семена фасоли"),
		"description": tr("Семена для выращивания сладкой и сочной свёклы."),
		"type": "Семена",
		"item_type": "seeds",
		"purchase": 1,
		"sale": 100,
		"crop": 15,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_15.png"),
	},
	# crops
	28: {
		"caption": tr("Морковь"),
		"description": tr("Сладкая и хрустящая морковь."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 25,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/carrot.png"),
	},
	29: {
		"caption": tr("Картофель"),
		"description": tr("Питательный клубень для различных блюд."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 75,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/potato.png"),
	},
	30: {
		"caption": tr("Редис"),
		"description": tr("Острый и сочный корнеплод."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 50,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/radish.png"),
	},
	31: {
		"caption": tr("Кочан капусты"),
		"description": tr("Свежая и крепкая капуста."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/cabbage.png"),
	},
	32: {
		"caption": tr("Репчатый лук"),
		"description": tr("Ароматный лук для приправ и салатов."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/onion.png"),
	},
	33: {
		"caption": tr("Огурец"),
		"description": tr("Хрустящий и освежающий огурец."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/cucumber.png"),
	},
	34: {
		"caption": tr("Помидор"),
		"description": tr("Сочные томаты для любых блюд."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/tomato.png"),
	},
	35: {
		"caption": tr("Баклажан"),
		"description": tr("Темно-фиолетовый плод для жарки и запекания."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/eggplant.png"),
	},
	36: {
		"caption": tr("Перец"),
		"description": tr("Яркий и пикантный перец."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/pepper.png"),
	},
	37: {
		"caption": tr("Початок кукурузы"),
		"description": tr("Золотистые зерна для вкусного гарнира."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/corn.png"),
	},
	38: {
		"caption": tr("Пастернак"),
		"description": tr("Деликатный вкус и полезные свойства."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/parships.png"),
	},
	39: {
		"caption": tr("Чеснок"),
		"description": tr("Ароматная пряность для усиления вкуса."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/garlic.png"),
	},
	40: {
		"caption": tr("Свёкла"),
		"description": tr("Сладкая и яркая, идеальна для салатов и супов."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/beet.png"),
	},
	41: {
		"caption": tr("Репа"),
		"description": tr("Круглый и плотный корнеплод."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/turnip.png"),
	},
	42: {
		"caption": tr("Фасоль"),
		"description": tr("Прекрасный источник белка, подходит для гарниров."),
		"type": "Урожай",
		"item_type": "crop",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/crops/greenbeen.png"),
	},
	# spoiled crops
	43: {
		"caption": tr("Испорченная морковь"),
		"description": tr("Морковь, потерявшая свою свежесть."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_1.png"),
	},
	44: {
		"caption": tr("Испорченный картофель"),
		"description": tr("Клубень, поражённый гнилью."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_2.png"),
	},
	45: {
		"caption": tr("Испорченный редис"),
		"description": tr("Корнеплод, покрытый пятнами гнили."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_3.png"),
	},
	46: {
		"caption": tr("Испорченный кочан капусты"),
		"description": tr("Капуста, начавшая разлагаться."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_4.png"),
	},
	47: {
		"caption": tr("Испорченный репчатый лук"),
		"description": tr("Лук, потерявший свой аромат."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_5.png"),
	},
	48: {
		"caption": tr("Испорченный огурец"),
		"description": tr("Огурец, утративший хрусткость и свежесть."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_6.png"),
	},
	49: {
		"caption": tr("Испорченный помидор"),
		"description": tr("Томат, покрытый плесенью и гнилью."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_7.png"),
	},
	50: {
		"caption": tr("Испорченный баклажан"),
		"description": tr("Плод, покрытый темными пятнами и гнилью."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_8.png"),
	},
	51: {
		"caption": tr("Испорченный перец"),
		"description": tr("Перец, начало которого уже разложилось."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_9.png"),
	},
	52: {
		"caption": tr("Испорченный початок кукурузы"),
		"description": tr("Кукуруза, поражённая грибком и гнилью"),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_10.png"),
	},
	53: {
		"caption": tr("Испорченный пастернак"),
		"description": tr("Корнеплод, начавший разлагаться"),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_11.png"),
	},
	54: {
		"caption": tr("Испорченный чеснок"),
		"description": tr("Чеснок, утративший свои полезные свойства"),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_12.png"),
	},
	55: {
		"caption": tr("Испорченная свёкла"),
		"description": tr("Свёкла, покрытая пятнами гнили"),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_13.png"),
	},
	56: {
		"caption": tr("Испорченная репа"),
		"description": tr("Корнеплод, поражённый гнилью"),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_14.png"),
	},
	57: {
		"caption": tr("Испорченная фасоль"),
		"description": tr("Потемневшие и размягченные бобы, непригодные для еды."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/spoilages/crop_15.png"),
	},
	# trash
	58: {
		"caption": tr("Ботва"),
		"description": tr("Листья и стебли после сбора урожая. Полезна для создания компоста или кормления животных."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/trash/trash_1.png"),
	},
	59: {
		"caption": tr("Ветка"),
		"description": tr("Отломанные или срезанные ветви деревьев. Используются в строительстве, для разжигания костров или производства удобрений."),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/trash/trash_2.png"),
	},
	60: {
		"caption": tr("Сорняки"),
		"description": tr("Неприхотливые растения, которые мешают росту культур. Могут быть использованы в компосте"),
		"type": "Отходы",
		"item_type": "compost",
		"decay": 1, # seconds
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/trash/trash_2.png"),
	},
	# Compost
	61: {
		"caption": tr("Обычный компост"),
		"description": tr(""),
		"type": "Удобрения",
		"item_type": "fertilizer",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/trash/trash_2.png"),
	},
	62: {
		"caption": tr("Высококачественный компост"),
		"description": tr(""),
		"type": "Удобрения",
		"item_type": "fertilizer",
		"purchase": 1,
		"sale": 100,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/trash/trash_2.png"),
	},
}
