extends Node2D

class_name Crops
var crops:Dictionary = {
	"atlas": load("res://assets/resources/farming/crops.png"),
	"width": 16,
	"height": 32,
	"check_watering": 10,
	"probability_spoilage": 5,
	# spring crops
	1: {
		"caption" = tr("Морковь"),
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 25,
		"growth_level" = 5,
		"mortality" = 5,
		"productivity" = [1,5],
		"X" = 0, "Y" = 0,
		"item" = 28,
		"spoilage" = 43,
	},
	2: {
		"caption" = tr("Картофель"),
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 50,
		"growth_level" = 6, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 32,
		"item" = 29,
		"spoilage" = 44,
	},
	3: {
		"caption" = tr("Редис"),
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 35,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 64,
		"item" = 30,
		"spoilage" = 45,
	},
	4: {
		"caption" = tr("Капуста"),
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 75,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 96,
		"item" = 31,
		"spoilage" = 46,
	},
	5: {
		"caption" = tr("Репчатый лук"),
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 15,
		"growth_level" = 5, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 128,
		"item" = 32,
		"spoilage" = 47,
	},
	# summer crops
	6: {
		"caption" = tr("Огурцы"),
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 36,
		"growth_level" = 6, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 112, "Y" = 0,
		"item" = 33,
		"spoilage" = 48,
	},
	7: {
		"caption" = tr("Томат"),
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 43,
		"growth_level" = 6, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 112, "Y" = 32,
		"item" = 34,
		"spoilage" = 49,
	},
	8: {
		"caption" = tr("Баклажан"),
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 35,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 112, "Y" = 64,
		"item" = 35,
		"spoilage" = 50,
	},
	9: {
		"caption" = tr("Перец"),
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 12,
		"growth_level" = 5, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 112, "Y" = 96,
		"item" = 36,
		"spoilage" = 51,
	},
	10: {
		"caption" = tr("Кукуруза"),
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 52,
		"growth_level" = 6, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 112, "Y" = 128,
		"item" = 37,
		"spoilage" = 52,
	},

	# autumn crops
	11: {
		"caption" = tr("Пастернак"),
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 81,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 224, "Y" = 0,
		"item" = 38,
		"spoilage" = 53,
	},
	12: {
		"caption" = tr("Чеснок"),
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 84,
		"growth_level" = 5, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 224, "Y" = 32,
		"item" = 39,
		"spoilage" = 54,
	},
	13: {
		"caption" = tr("Свёкла"),
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 80,
		"growth_level" = 6, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 224, "Y" = 64,
		"item" = 40,
		"spoilage" = 55,
	},
	14: {
		"caption" = tr("Репа"),
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 15,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 224, "Y" = 96,
		"item" = 41,
		"spoilage" = 56,
	},
	15: {
		"caption" = tr("Фасоль"),
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 15,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [2,4], 
		"X" = 224, "Y" = 128,
		"item" = 42,
		"spoilage" = 57,
	},
}
