extends Node2D

class_name Crops
var crops:Dictionary = {
	"atlas": load("res://assets/resources/farming/crops.png"),
	"width": 16,
	"height": 32,
	"probability_spoilage": 5,
	# spring crops
	1: {
		"caption" = 'crops.carrot',
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 5.0,
		"growth_level" = 5,
		"mortality" = 150,
		"productivity" = [1,1],
		"X" = 0, "Y" = 0,
		"item" = 28,
		"spoilage" = 43,
	},
	2: {
		"caption" = 'crops.potato',
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 120.0,
		"growth_level" = 6, 
		"mortality" = 150,
		"productivity" = [1,2], 
		"X" = 0, "Y" = 32,
		"item" = 29,
		"spoilage" = 44,
	},
	3: {
		"caption" = 'crops.radish',
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 80.0,
		"growth_level" = 4, 
		"mortality" = 150,
		"productivity" = [1,1], 
		"X" = 0, "Y" = 64,
		"item" = 30,
		"spoilage" = 45,
	},
	4: {
		"caption" = 'crops.cabbage',
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 200.0,
		"growth_level" = 4, 
		"mortality" = 150,
		"productivity" = [1,1], 
		"X" = 0, "Y" = 96,
		"item" = 31,
		"spoilage" = 46,
	},
	5: {
		"caption" = 'crops.onion',
		"type" = "vegetable", 
		"season" = ["spring"],
		"environment" = "soil",
		"growth_rate" = 90.0,
		"growth_level" = 5, 
		"mortality" = 150,
		"productivity" = [1,1], 
		"X" = 0, "Y" = 128,
		"item" = 32,
		"spoilage" = 47,
	},
	# summer crops
	6: {
		"caption" = 'crops.cucumber',
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 110.0,
		"growth_level" = 6, 
		"mortality" = 150,
		"productivity" = [1,2], 
		"X" = 112, "Y" = 0,
		"item" = 33,
		"spoilage" = 48,
	},
	7: {
		"caption" = 'crops.tomato',
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 150.0,
		"growth_level" = 6, 
		"mortality" = 150,
		"productivity" = [1,3], 
		"X" = 112, "Y" = 32,
		"item" = 34,
		"spoilage" = 49,
	},
	8: {
		"caption" = 'crops.eggplant',
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 175.0,
		"growth_level" = 4, 
		"mortality" = 150,
		"productivity" = [1,2], 
		"X" = 112, "Y" = 64,
		"item" = 35,
		"spoilage" = 50,
	},
	9: {
		"caption" = 'crops.pepper',
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 100.0,
		"growth_level" = 5, 
		"mortality" = 150,
		"productivity" = [1,3], 
		"X" = 112, "Y" = 96,
		"item" = 36,
		"spoilage" = 51,
	},
	10: {
		"caption" = 'crops.corn',
		"type" = "vegetable", 
		"season" = ["summer"],
		"environment" = "soil",
		"growth_rate" = 225.0,
		"growth_level" = 6, 
		"mortality" = 150,
		"productivity" = [1,3], 
		"X" = 112, "Y" = 128,
		"item" = 37,
		"spoilage" = 52,
	},

	# autumn crops
	11: {
		"caption" = 'crops.parsnips',
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 65.0,
		"growth_level" = 4, 
		"mortality" = 150,
		"productivity" = [1,1], 
		"X" = 224, "Y" = 0,
		"item" = 38,
		"spoilage" = 53,
	},
	12: {
		"caption" = 'crops.garlic',
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 75.0,
		"growth_level" = 5, 
		"mortality" = 150,
		"productivity" = [1,2], 
		"X" = 224, "Y" = 32,
		"item" = 39,
		"spoilage" = 54,
	},
	13: {
		"caption" = 'crops.beet',
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 65.2,
		"growth_level" = 6, 
		"mortality" = 150,
		"productivity" = [1,1], 
		"X" = 224, "Y" = 64,
		"item" = 40,
		"spoilage" = 55,
	},
	14: {
		"caption" = 'crops.turnip',
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 50.5,
		"growth_level" = 4, 
		"mortality" = 150,
		"productivity" = [1,1], 
		"X" = 224, "Y" = 96,
		"item" = 41,
		"spoilage" = 56,
	},
	15: {
		"caption" = 'crops.bean',
		"type" = "vegetable", 
		"season" = ["autumn"],
		"environment" = "soil",
		"growth_rate" = 80.6,
		"growth_level" = 4, 
		"mortality" = 150,
		"productivity" = [1,2], 
		"X" = 224, "Y" = 128,
		"item" = 42,
		"spoilage" = 57,
	},
}
